<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>Innocap.Legacy.Domain</RootNamespace>
    <AssemblyName>Innocap.Legacy.Domain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <!-- Newtonsoft here, STJ in Api — smell #12 -->
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
